### ISSUE TITLE
mbpfan on iMac27 mid2011 not working

### ISSUE THREAD

**Issue by CalamarJuan** [dgraziotin/mbpfan#102]
Hello and thanks for this precise tutorial, it is very clear and simple to follow.
Unfortunately in my case it did not do what I needed, maybe someone here has a similar issue:
I have an iMac27 mid2011 with Ubuntu 16.04, native installed (no iOs at all), and now changed the HDD into SSD. 
Since then, the fan nr.2 starts rising more and more up untill it reaches aprox. 5.500. 
This machine has 2 main fans and nr.2 obviously is missing the signal from the HDD. 
I have tried to name them in the mbpfan.conf like:
min_fan1_speed = 2000
max_fan1_speed = 6200
min_fan2_speed = 2000
max_fan2_speed = 2100
Also tried different values, but no reaction, even if I use the normal version of mbpfan.conf, without giving nr. to the fan, mbpfan doesnt seem to cause any changes.
The values from the sensors (supose to be nr. 20&21) are showing 9ºC both
Anyone who could help here please? Thanks in advance!
The output of "sensors" is:
`
j@iMac:~$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +50.0°C  (high = +80.0°C, crit = +86.0°C)
Core 0:         +48.0°C  (high = +80.0°C, crit = +86.0°C)
Core 1:         +48.0°C  (high = +80.0°C, crit = +86.0°C)
Core 2:         +50.0°C  (high = +80.0°C, crit = +86.0°C)
Core 3:         +49.0°C  (high = +80.0°C, crit = +86.0°C)

applesmc-isa-0300
Adapter: ISA adapter
ODD :        1999 RPM  (min = 2000 RPM, max = 2500 RPM)
HDD :        4908 RPM  (min = 2000 RPM, max = 5500 RPM)
CPU :         939 RPM  (min =  940 RPM, max = 2100 RPM)
TA0P:         +22.5°C  
TA0V:         +23.0°C  
TA0p:         +28.0°C  
TC0H:         +42.2°C  
TC0P:         +44.5°C  
TC0c:         +46.0°C  
TC0h:         +42.2°C  
TC0p:         +44.5°C  
TC1c:         +46.0°C  
TC2c:         +46.0°C  
TC3c:         +46.0°C  
TCGc:         +46.0°C  
TCSc:         +46.0°C  
TCXc:         +47.0°C  
TG0D:         +51.5°C  
TG0H:         +50.0°C  
TG0d:         +51.5°C  
TG0h:         +50.0°C  
TG0p:         +51.0°C  
TH0O:          +9.0°C  
TH1O:          +9.0°C  
TL0P:         +47.0°C  
TL0V:         +43.2°C  
TL0p:         +60.2°C  
TL1P:         +48.5°C  
TL1V:         +43.5°C  
TL1p:         +48.5°C  
TL1v:         +43.5°C  
TL2V:         +50.2°C  
TLAV:         +47.0°C  
TLBV:         +50.2°C  
TLCV:         +43.2°C  
TO0P:         +43.0°C  
TO0p:         +44.0°C  
TPCD:         +55.0°C  
TS0P:         +39.2°C  
TS0V:         +34.2°C  
TS0p:         +39.2°C  
TS2P:         +39.5°C  
TS2V:         +37.8°C  
TS2p:         +39.5°C  
Tm0P:         +45.5°C  
Tm0p:         +45.5°C  
Tp1P:         +56.2°C  
Tp1p:         +56.2°C  
Tp2H:         +71.5°C  
Tp2h:         +71.5°C  
Tp3H:         +62.2°C  
Tp3h:         +62.2°C  

j@iMac:~$ `

**Comment by dgraziotin** [comment]
Hello @CalamarJuan. Could you please checkout out [mbpfan v2.0.0](https://github.com/dgraziotin/mbpfan/releases/tag/v2.0.0) to see if that is still the case?
