### ISSUE TITLE
Update AUR for mbpfan v2.0.0

### ISSUE THREAD

**Issue by dgraziotin** [dgraziotin/mbpfan#106]
There is the need to update [mbpfan AUR entry](https://aur.archlinux.org/packages/mbpfan-git/) for v2.0.0.

**Comment by dgraziotin** [comment]
@Yamakaky, I know you will never believe I actually released it. Are you still willing to update AUR?

**Comment by Yamakaky** [comment]
Done!

**Comment by dgraziotin** [comment]
Many thanks!
