### ISSUE TITLE
Exceeds maximum fan speed on iMac 27" late 2012

### ISSUE THREAD

**Issue by LukeLR** [dgraziotin/mbpfan#114]
@Hello everyone,
first things first: thanks A LOT for your awesome work in this project. We need more such small open source tools like this one, they save lifes :smile: 

Regarding the issue: I just compiled and installed using the Arch Linux AUR-Package on my iMac 27" late 2012 running 4.10.11-1-ARCH. After launching, my fans went immediately WAY over the maximum: The maximum fan speed for my iMac is at 2600 RPM, directly after launching they went up to ~4000 RPM. Had to `killall mbpfan` in order to correct things.

Still, my CPU is considerably hot right now (95° Celsius), and regular Linux fan control kept the fan speed quite low (1.600RPM, the "idle" value) for no known reason, so that's why I looked for some fan controll tool. Now, after killing mbpfan, my fan speed is still at 2600RPM (it's maximum) and behaving normally now (adjusting with CPU temp), so whatever had caused the linux kernel to keep fan speed so low, launching and killing mbpfan has fixed it :smile:

**Comment by dgraziotin** [comment]
Hello, I am assuming you [configured mbpfan](https://ineed.coffee/3838/a-beginners-tutorial-for-mbpfan-under-ubuntu/) before launching it?

**Comment by dgraziotin** [comment]
Please reopen in case you are still facing issues.
