### ISSUE TITLE
minor programming issue

### ISSUE THREAD

**Issue by Ndolam** [dgraziotin/mbpfan#117]
In main.c in check_requirements() in two places opendir() might be called without calling closedir().
This only happens if coretemp and/or applesmc are built in but not modules. 
I believe you want to add closedir(dir) after the "if (ENOENT == errno)" block in two places.

Incidentally, is it not the case that the opendir()... check subsumes the popen(lsmod|grep) code?
If so, you could eliminate a few redundant lines of code and use the faster code path which just
does an opendir() instead of a couple of fork()/exec()s.  Not that mbpfan is executed often enough for
that to be a big deal.

Cheers.

**Comment by dgraziotin** [comment]
adding `closedir(dir)` after `if (ENOENT == errno)` makes sense, thanks.

now, regarding using opendir() and remove popen(). It also actually seem to make sense. After all, if no modules are loaded (or built-in), the path won't exist. Is that what you are suggesting here?
