### ISSUE TITLE
bad macro definitions

### ISSUE THREAD

**Issue by Ndolam** [dgraziotin/mbpfan#118]
In mbpfan.c there is the code
#define min(a,b) a < b ? a : b
#define max(a,b) a > b ? a : b
which is buggy.  The bug issn't manifested in the current code, but to protect against future changes
I suggest you use 
#define min(a,b) ((a) < (b) ? (a) : (b))
#define max(a,b) ((a) > (b) ? (a) : (b))
which makes the macros safer when an argument might be a complex expression.

**Comment by dgraziotin** [comment]
Thanks, will add this in the next minor revision!
