### ISSUE TITLE
mbpfan ignores some of my sensors

### ISSUE THREAD

**Issue by ohthehugemanatee** [dgraziotin/mbpfan#120]
mbpfan seems to only take my CPU core sensors into account. This is a problem, since there are lots of areas on my laptop that heat up, and the same fan is supposed to keep them all cool. Here's a sample output from `sensors` and `sudo service mbpfan status`:

```
$ sensors
applesmc-isa-0300
Adapter: ISA adapter
Exhaust  :   2734 RPM  (min = 2000 RPM, max = 6200 RPM)
TA0P:         +49.0°C  
TB0T:         +40.5°C  
TB1T:         +40.5°C  
TB2T:         +37.5°C  
TC0E:         +68.5°C  
TC0F:         +70.0°C  
TC0J:          +1.5°C  
TC0P:         +62.0°C  
TC1C:         +66.0°C  
TC2C:         +66.0°C  
TCGC:         +66.0°C  
TCSA:         +66.0°C  
TCTD:          -0.2°C  
TCXC:         +67.5°C  
TG1D:         +70.0°C  
TM0P:         +46.5°C  
TM0S:         +58.0°C  
TPCD:         +78.0°C  
Th1H:         +54.2°C  
Ts0P:         +36.0°C  
Ts0S:         +47.0°C  

BAT0-virtual-0
Adapter: Virtual device
temp1:        +40.9°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +67.0°C  (high = +87.0°C, crit = +105.0°C)
Core 0:        +67.0°C  (high = +87.0°C, crit = +105.0°C)
Core 1:        +67.0°C  (high = +87.0°C, crit = +105.0°C)

$ sudo service mbpfan status

● mbpfan.service - A fan manager daemon for MacBook Pro
   Loaded: loaded (/etc/systemd/system/mbpfan.service; enabled; vendo
   Active: active (running) since Sat 2017-06-17 23:27:59 CEST; 15min
 Main PID: 8111 (mbpfan)
    Tasks: 1 (limit: 4915)
   Memory: 848.0K
      CPU: 502ms
   CGroup: /system.slice/mbpfan.service
           └─8111 /usr/sbin/mbpfan -fv

Jun 17 23:43:14 Tesla mbpfan[8111]: Old Temp 68: New Temp: 66, Fan Sp
Jun 17 23:43:14 Tesla mbpfan[8111]: Sleeping for 4 seconds
Jun 17 23:43:18 Tesla mbpfan[8111]: Old Temp 66: New Temp: 67, Fan Sp
Jun 17 23:43:18 Tesla mbpfan[8111]: Sleeping for 4 seconds
```

Note that sensor TPCD is reading 78 degrees, but mbpfan only cares that the core is at 66. I'm on a late 2012 Macbook pro, running Ubuntu 17.04 with 64 bit kernel 4.10.0-22-generic #24-Ubuntu. I can't find any documentation about what those various sensors mean; I suspect it's the video card, though. 

Regardless, it would be great to be able to configure the sensors mbpfan uses... or better yet, have it take the highest temperature from all the sensors, rather than just the CPU cores.

**Comment by dgraziotin** [comment]
Hello and thank you for this report. This seems to make sense, but it could add a lot of code complexity. The beauty of mbpfan is in its simplicity as it is supposed to work on all systems (all systems do have a cpu, after all). But your case is interesting because it highlights a situation when mbpfan does its job but not efficiently. I will play with the sensors command and see what it does and where these values come from. In the worst case, would you be willing to provide me some command outputs?

**Comment by ohthehugemanatee** [comment]
Of course! I'd be happy to provide whatever information you need.

FWIW, this wasn't a problem when I ran Linux Mint based on Ubuntu 16.04. All the other sensor outputs appeared when I switched to Ubuntu 17.04 . So I guess that the kernel was bundling the sensors together before, and now keeps them separate?

Very happy to  give whatever information you need.

**Comment by dgraziotin** [comment]
So I did explore ` sensors` and the structure of `/sys/devices/platform/applesmc.768`.

Output of sensors
```
coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +49.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:         +48.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:         +48.0°C  (high = +105.0°C, crit = +105.0°C)
Core 2:         +47.0°C  (high = +105.0°C, crit = +105.0°C)
Core 3:         +48.0°C  (high = +105.0°C, crit = +105.0°C)

applesmc-isa-0300
Adapter: ISA adapter
Main :       1201 RPM  (min = 1200 RPM, max = 3028 RPM)
TA0P:         +16.0°C  
TA0V:         +29.5°C  
TA0p:         +36.0°C  
TC0E:         -55.5°C  
TC0F:         -54.0°C  
TC0J:          +1.5°C  
TC0P:         +47.0°C  
TC0T:          -0.2°C  
TC0c:         +48.0°C  
TC0p:         +47.0°C  
TC1c:         +48.0°C  
TC2c:         +47.0°C  
TC3c:         +48.0°C  
TCGc:         +49.0°C  
TCSc:         +49.0°C  
TCXR:         -56.0°C  
TCXc:         +49.0°C  
TCXr:         -56.0°C  
TH0A:        -127.0°C  
TH0B:        -127.0°C  
TH0C:        -127.0°C  
TH0F:        -127.0°C  
TH0O:          +9.0°C  
TH0P:        -127.0°C  
TH0R:        -127.0°C  
TH0a:        -127.0°C  
TH0b:        -127.0°C  
TH0c:        -127.0°C  
TH1A:         +38.0°C  
TH1B:         +39.0°C  
TH1C:         +38.0°C  
TH1F:         -46.0°C  
TH1O:          +9.0°C  
TH1P:        -127.0°C  
TH1R:         -46.0°C  
TH1a:         +38.0°C  
TH1b:         +39.0°C  
TH1c:         +38.0°C  
TI0p:         +53.8°C  
TL0P:         +42.5°C  
TL0V:        -127.0°C  
TL0p:         +42.5°C  
TL1P:         +41.2°C  
TL1V:         +42.2°C  
TL1o:         +42.2°C  
TL1p:         +41.2°C  
TL1v:         +42.2°C  
TM0P:         +47.2°C  
TM0V:         +47.8°C  
TM0p:         +47.2°C  
TMXP:         +47.2°C  
TPCD:         +54.0°C  
TS0V:         +40.0°C  
Tb0P:         +52.8°C  
Tb0p:         +52.8°C  
Tm0P:         +45.2°C  
Tm0p:         +45.2°C  
Tm2P:         +45.5°C  
Tm2p:         +45.5°C  
Tp2F:         +43.8°C  
Tp2H:         +43.8°C  
Tp2h:         +43.8°C
```

It is my understanding that the files at `/sys/devices/platform/applesmc.768` contain label (tempXX_label) and values (tempXX_input) for those sensors. For example, the last value reported by sensors for Tp2h is temp62 on my system:

```
ubuntu@ubuntu:/sys/devices/platform/applesmc.768$ cat temp62_label 
Tp2h
ubuntu@ubuntu:/sys/devices/platform/applesmc.768$ cat temp62_input 
44000
```

I am not sure how the rounding (44->43.8) works. I could not find any documentation for these sensors, unfortunately. Furthermore, some report negative temp values:

```
$ cat temp*_input
47750
49000
48000
49000
50000
49000
-55250
49750
-55250
-127000
16250
-127000
-127000
-127000
9000
-127000
-127000
-127000
-127000
-127000
38000
29500
39000
38000
-46000
9000
-127000
-46000
38000
39000
38000
53750
36250
42750
-127000
42750
41250
42500
42500
41250
42500
48000
48250
-53750
48000
48000
54000
40250
52750
52750
45500
45500
46250
46250
-51750
44000
44000
44000
2000
47750
-250
48000
```

My philosophy in this case is "it's not broken, don' t touch it". Given my ignorance in how applesmc works, I am afraid I do not have the time for exploring this. PR are always welcome!.
