### ISSUE TITLE
Test suite does not fully run because of polling interval value

### ISSUE THREAD

**Issue by yulert** [dgraziotin/mbpfan#136]
Hello,

I have installed mpbfan via the AUR on Manjaro (Kernel 4.9.4) and although the systemctl service seems to be running I am not sure is doing anything. I am not even sure the config file is being read. I am using a late 2014 macbook pro.

As per the installation instructions, I decided to run the tests to ensure everything is OK but the test suite fails to complete with:

sudo mpbfan -t
Starting the tests..
It is normal for them to take a bit to finish.
polling_interval is not 1 
Tests run: 5

Also not sure if this a problem or not but the tests will only run as sudo, if i run mbpfan without sudo then I get no sensors were detected please contact the developer.

I tried setting the polling_interval to 1 in the etc/mbpfan.conf but I still dont get that sweet all tests passed message. It still complains that the polling_interval is not 1.

Any pointers to resolve the issue would be appreciated.

Thank you.

**Comment by dgraziotin** [comment]
Hi,

We are in the process of rewriting certain parts of the tests. Mbpfan v2.0.2 (but also v2.0.0 from AUR) should work fine anyway.
Tests run with sudo only, as also mbpfan needs sudo access.
