### ISSUE TITLE
[Request] Options for less logging via syslog

### ISSUE THREAD

**Issue by linuxpng** [dgraziotin/mbpfan#138]
The default for mbpfan to log to syslog seems to be every 7 seconds via the "polling_interval" option in mbpfan.  

1) Does this option only control how often the speed changes are logged via syslog?
1a) If so the generated config file could you some clarity in what this field is actually doing.

2) If not, is there a way to make mbpfan less chatty in syslog output?

$ head -n1 /var/log/syslog
Aug 30 06:25:03 CanisMajor mbpfan[1033]: Old Temp 59: New Temp: 61, Fan Speed: 2000

$ grep "Fan Speed" /var/log/syslog | wc -l
1117

**Comment by andrewgaul** [comment]
One of the commits from #135 should address this. @sasanj

**Comment by dgraziotin** [comment]
Folks, thank you so much for all these PR! I am notoriously slow to review them, but eventually they will get through.

Dr. Daniel Graziotin
@dgraziotin
ineed.coffee

**Comment by sasanj** [comment]
For a temporary fix, simply open this file `/lib/systemd/system/mbpfan.service` and remove '`v`' flag from the line [`ExecStart=/usr/sbin/mbpfan -fv`](https://github.com/dgraziotin/mbpfan/blob/bd92a25b3dc7bffb576eed556d86831f33fc1dce/mbpfan.service#L8), save and restart service (`systemctl restart mpbfan`).

**Comment by dgraziotin** [comment]
Fixed in #135 and merged in master. Will release a new public version today.
