### ISSUE TITLE
MBP 2012 .. fan always on 6200rpm with 50C  on Fedora 26

### ISSUE THREAD

**Issue by fellipeh** [dgraziotin/mbpfan#139]
Hi,

My fan always on 6200rpm on 52C... it's normal?
I run all test of mbpfan and *all* passed...I have mbpfan as service, and started...

I'm using Fedora 26...

It's normal?

**Comment by sasanj** [comment]
From where these measurement come from? What are the contents of the configuration file?

**Comment by dgraziotin** [comment]
Also, are you doing CPU-intensive tasks?

Dr. Daniel Graziotin 
https://ineed.coffee/

**Comment by rmmm** [comment]
Hello @fellipeh 

I am running a Mid-2012 MacBook Pro on Fedora 26 and have not experienced this issue. Do you have lm-sensors installed? If not, please install it using `dnf install lm_sensors`.

Then please provide the output of running `sensors`. For example...

mbp:~ $ sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +39.0°C  (high = +87.0°C, crit = +105.0°C)
Core 0:        +39.0°C  (high = +87.0°C, crit = +105.0°C)
Core 1:        +38.0°C  (high = +87.0°C, crit = +105.0°C)

BAT0-virtual-0
Adapter: Virtual device
temp1:        +21.2°C  

applesmc-isa-0300
Adapter: ISA adapter
Exhaust  :   2000 RPM  (min = 2000 RPM, max = 6200 RPM)
TA0P:         +28.2°C  
TB0T:         +21.0°C  
TB1T:         +31.0°C  
TB2T:         +30.2°C  
TC0E:         +39.5°C  
TC0F:         +40.8°C  
TC0J:          +1.0°C  
TC0P:         +36.2°C  
TC1C:         +40.0°C  
TC2C:         +38.0°C  
TCGC:         +41.0°C  
TCSA:         +38.0°C  
TCTD:          +0.0°C  
TCXC:         +40.2°C  
TG1D:         +40.8°C  
TM0P:         +27.2°C  
TM0S:         +35.2°C  
TPCD:         +51.0°C  
Th1H:         +32.0°C  
Ts0P:         +23.5°C  
Ts0S:         +25.0°C

If you could also provide the output of `top | head -n 15`

Also, as @sasanj has asked, have you made any changes to the default configuration of mbpfan? If so, please provide your config file.

**Comment by dgraziotin** [comment]
Please reopen in case you are still facing issues.
