### ISSUE TITLE
(Testing Report) Works with Mac Pro 3,1

### ISSUE THREAD

**Issue by dmutters** [dgraziotin/mbpfan#140]
I didn't see any contact info, so I figured I'd drop this here.
I just installed mbpfan on a dual Xeon Mac Pro 3,1 from early 2008, and it works great.  Thanks!

**Comment by andrewgaul** [comment]
@dmutters Can you submit a pull request adding this to https://github.com/dgraziotin/mbpfan#tested-macbook-models?

**Comment by dmutters** [comment]
Done.

**Comment by andrewgaul** [comment]
@dmutters I don't see you pull request here:

https://github.com/dgraziotin/mbpfan/pulls

**Comment by dmutters** [comment]
I edited the Readme.md file and clicked, "propose file change".  Sorry, I'm new to github; if there's a better method, please let me know.
