### ISSUE TITLE
Replicate macos fan behaviour to avoid overheating

### ISSUE THREAD

**Issue by ellipticaldoor** [dgraziotin/mbpfan#141]
I hace a MacBookPro11,5 from 2015,

When I run linux with mbpfan it works, if I play a game or something cpu intensive the fans increase their speed.

The thing is that most of the time is fans are silent when I use linux. If a restart into macos the fans immediately because the laptop was very hot.

I reboot again into linux the fans stop until the temperature increments a lot more.

I'm worried that this behaviour can damage the laptop, there is any solution for this?

**Comment by gaul** [comment]
Can you run `dmesg` to see if it contains overheating warnings?  The CPU will actually run at lower frequencies if cooling is not sufficient.  mbpfan should avoid this situation although it may require some tuning of `high_temp` in `mbpfan.conf`.

**Comment by ellipticaldoor** [comment]
I did
```
dmesg | warning
```

but I didn't found nothing.

Do you have any advice for tuning mbpfan.conf?

**Comment by dgraziotin** [comment]
Hi Miguel,

To doublecheck, are you sure that mbpfan is actually running?

    ps aux | grep mbpfan

should return something.

Also, you are not running any other fan control system, are you?

Cheers,

Dr. Daniel Graziotin 
https://ineed.coffee/

**Comment by ellipticaldoor** [comment]
Yes it's running and I don't have any other fan control system

**Comment by gaul** [comment]
Please run `mbpfan -f -v` and let's see what the state of the sensors and fans are.

**Comment by dgraziotin** [comment]
Please reopen in case you are still facing issues.

**Comment by kontheocharis** [comment]
I've got the same problem on a MacBook Pro 11,5
