### ISSUE TITLE
polling_interval is not 1

### ISSUE THREAD

**Issue by BeratAdemi** [dgraziotin/mbpfan#145]
I installed mlbfan on my Macbook Air 2015 (7,2) and when I run the tests it shows the output "polling_intervall is not 1".

I tried to change the polling_intervall in the config file but that did not seem to make any difference.

Is that something to be concerned about?

**Comment by dgraziotin** [comment]
Hello, can you please try with the latest released version and open this again in case it is still happening? Cheers
