### ISSUE TITLE
rename to macfan

### ISSUE THREAD

**Issue by davidak** [dgraziotin/mbpfan#146]
It does not only work on MacBook Pros, but also on other Mac hardware. This would clarify the purpose and prevent confusion with the original script and is similar to thinkfan.

But would break some packages downstream. It could be forked again in the next version. Or should we just name our service different in NixOS? (https://github.com/NixOS/nixpkgs/issues/32266)

**Comment by dgraziotin** [comment]
Hi, thank you for your suggestion. 
I have renamed this project once already. It used to be called Fan-Control-Daemon. Renaming it has been a bit of a pain back then (some distros had incorporated it already). Renaming it once again would be even more confusing--people also [talk about it to some extent](https://www.google.de/search?q=%22mbpfan%22&)). While you are perfectly right with your reasoning, I am afraid that the costs would outweigh the benefits.

**Comment by davidak** [comment]
I understand and respect your choice.
