### ISSUE TITLE
I think i have a perms issue

### ISSUE THREAD

**Issue by nvrslpn** [dgraziotin/mbpfan#147]
Hello, thank you so much for creating this source for everyone to use. that's very nice of you, very old school of you too, love it! That said, after installing, compiling, running and and configuring, I get a little bit different read out when I look at my running processes than what you stated should be. I think this is leading to the program not having the right perms to run when its needed. This is what I'm getting.
::::::::::::::::::::::::::
nvrslpn@ORION:~$ ps aux | grep mbpfan
root       611  0.0  0.0   7900   484 ?        Ss   20:10   0:00 /usr/sbin/mbpfan -f
nvrslpn   2282  0.0  0.1  21452  1032 pts/0    S+   20:13   0:00 grep --color=auto mbpfan
nvrslpn@ORION:~$ 
:::::::::::::::::::::::::
I noticed at boot up the fans kick into high gear, but then slow way down when the OS starts up. I'm running Ubuntu 17.10 on a 2007 iMac. My question is why I don't have the "v" after the "-f" . is there a quick and dirty fix for this, like a sudo grep or something. This toaster over I call a computer already fried one HDD when it had mac OS on it and now that I put an SSD in it I don't want this one to fry too. Any help would be very much appreciated.

**Comment by dgraziotin** [comment]
Hello, the missing _v_ part is not an issue (see #149). The initial kick of the fans is also normal. If you notice that the fans are changing their speeds whenever you use heavier apps, it seems it's working. Please note you can change mbpfan behavior by tweaking the settings.
