### ISSUE TITLE
is this a problem?

### ISSUE THREAD

**Issue by lemontrachet** [dgraziotin/mbpfan#149]
Thanks for the app. The fans seem under control. In your tutorial, you say I should look for a line ending -fv. I have the following:

/usr/sbin/mbpfan -f

Is this ok?

OS is latest Ubuntu 16

Thanks again

**Comment by dgraziotin** [comment]
Hi! Yes, this was a recent change. Will update accordingly. All is well.

Dr. Daniel Graziotin  
https://ineed.coffee
@dgraziotin

**Comment by lemontrachet** [comment]
Thanks and merry Christmas!
