### ISSUE TITLE
mbpfan not turning on

### ISSUE THREAD

**Issue by SirWindfield** [dgraziotin/mbpfan#151]
Hey, it's my first installation of arch so if I do something wrong, please let me know!

I installed using the AUR package you listed within the readme file. `coretemp` and `applesmc` are enabled and the service is running on boot.
I even set the minimum fan speed to 3000 to try and take a look if they start properly.

I am running kernel version 4.15, MacBook12,1 Retina.

Maybe you can help me, I am pretty much clueless...

**Comment by trev-dev** [comment]
Also having an issue getting mbpfan to work 

`
roonie@roonux ~ $ lsmod | grep coretemp && lsmod | grep applesmc
coretemp               16384  0
applesmc               20480  0
input_polldev          16384  1 applesmc
`
systemctl states the service is enabled. Tests passed after make.

If I try to run the test mbpfan -t I get
`
Starting the tests..
It is normal for them to take a bit to finish.
mbpfan could not detect any fan. Please contact the developer.
`

**Comment by SirWindfield** [comment]
I clean installed arch again and it worked out of the box. I just made sure to install it right after I created a new user, I just pacstrap'ed before. I think I installed it earlier on using the root account. That might have broken it.
