### ISSUE TITLE
HSTS Certificate Expired

### ISSUE THREAD

**Issue by mk2soldier** [dgraziotin/mbpfan#153]
Hi! Great piece of software!
Howevere the website (https://ineed.coffee) certificate seems to be expired (15th of May)

**Comment by dgraziotin** [comment]
Whoops! Thanks, fixed!

https://www.ssllabs.com/ssltest/analyze.html?d=ineed.coffee&latest

Dr. Daniel Graziotin
@dgraziotin
ineed.coffee
