### ISSUE TITLE
Failed  - All Tests Passed

### ISSUE THREAD

**Issue by juan11perez** [dgraziotin/mbpfan#164]
First thank you for this project.
OS Ubuntu Desktop 18.04
Macbook Air
mbpfan-2.1.0.tar.gz

Followed your install tutorial, but do not get the all tests passed. see below log

```
juan@juan-MacBookAir:~/Downloads/mbpfan-2.1.0$ sudo make tests
make install
make[1]: Entering directory '/home/juan/Downloads/mbpfan-2.1.0'
install -d /usr/sbin
install -d /etc
install -d /lib/systemd/system
install -d /usr/share/doc/mbpfan
install bin/mbpfan /usr/sbin
install -m644 mbpfan.conf /etc
install -m644 README.md /usr/share/doc/mbpfan
install -d /usr/share/man/man8
install -m644 mbpfan.8.gz /usr/share/man/man8

******************
INSTALL COMPLETED
******************

A configuration file has been copied (might overwrite existing file) to /etc/mbpfan.conf.
See README.md file to have mbpfan automatically started at system boot.

Please run the tests now with the command
   sudo make tests

make[1]: Leaving directory '/home/juan/Downloads/mbpfan-2.1.0'
/usr/sbin/mbpfan -f -v -t
Starting the tests..
It is normal for them to take a bit to finish.
Using new sensor path for kernel >= 3.15.0 or some CentOS versions with kernel 3.10.0
Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp
Found 3 sensors
Found 1 fans
Using new sensor path for kernel >= 3.15.0 or some CentOS versions with kernel 3.10.0
Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp
Found 3 sensors
Could not read min_fan_speed from config file 
Tests run: 4
```
thank you

**Comment by gaul** [comment]
Which test failed?  I don't see any errors.

**Comment by juan11perez** [comment]
Thank you. In the result copied in my first post at the end it says it could not read min_fan_speed and it never produced the All Tests Passed per your instruction.

When I installed the previous version(2.0.2), it did the test and finished with All Tests Passed. 
I've now got it running and it works great. 
No more full blown fan speed.

**Comment by gaul** [comment]
Sorry the tests did not flag or propagate the error correctly which confused me.  I fixed this and the test logic for fan auto-detection which caused this error.  Please continue to use 2.1.0; none of the core logic has changed.

**Comment by juan11perez** [comment]
Thank you. I attempted 2.1.0 again and got the same error. 
back to 2.0.2 and there's no errors. "All TESTS PASSED"

**Comment by gaul** [comment]
Could you try master?

**Comment by juan11perez** [comment]
i downloaded the tar from this
https://github.com/dgraziotin/mbpfan/tags

**Comment by gaul** [comment]
Those are only the release versions.  You can check out master via:

```
git clone git@github.com:dgraziotin/mbpfan.git
```

This include the fix for the issue you uncovered.

**Comment by juan11perez** [comment]
yes, I downloaded from master and it now works. 
no errors
thank you
