### ISSUE TITLE
All fans assumed to have same min/max rpm

### ISSUE THREAD

**Issue by atisharma** [dgraziotin/mbpfan#167]
main.c:set_defaults sets a global max_fan_speed for all fans. On a Mac Pro at least, the max rpm varies per fan. This max value should be different per fan or at least set to the maximum over all fans.

**Comment by iridakos** [comment]
+1

**Comment by gaul** [comment]
@atisharma Does #171 resolve this issue?

**Comment by atisharma** [comment]
It does seem to. Thank you and thanks mikaelbjoern.
I can set min_fanX_speed in the .conf individually and it is respected. There are some problems I will raise in that issue.
