### ISSUE TITLE
Unable to pass tests and run mbpfan

### ISSUE THREAD

**Issue by RaelZero** [dgraziotin/mbpfan#169]
Hello,

After following the guides (the one included in the config and the [one for my distro](https://wiki.voidlinux.eu/Macbook)) and checking configurations (only required changing max temp to 87), I am unable to pass the tests, and the fan just does not start when launching `mbpfan` (or enabling it as a service).

I'm using a MacBook Pro 9.2 (i5 CPU if that matters) running Void Linux. Package version is 2.1.0. Other details are below. 

Also tried to compile from source on the latest commit and on the last commit when the guide was written (guide was written Dec '17, so 237eae73e8151e6c24210e027aecf7c461ff0338). Result does not change.

Are you able to assist? I know this is probably the epitome of a "special snowflake" setup, but would still appreciate support :)

Please let me know if I can be of any other help.

Thanks and keep up the good work!

Output of `uname -a`
```Linux myhostname 4.18.15_1 #1 SMP PREEMPT Thu Oct 18 12:33:28 UTC 2018 x86_64 GNU/Linux```

Output of `ldd --version`
```
musl libc (x86_64)
Version 1.1.20
```

Output of `mbpfan -f -v -t`
```
Starting the tests..
It is normal for them to take a bit to finish.
Using new sensor path for kernel >= 3.15.0 or some CentOS versions with kernel 3.10.0
Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp
Found 3 sensors
Found 1 fans
Using new sensor path for kernel >= 3.15.0 or some CentOS versions with kernel 3.10.0
Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp
Found 3 sensors
Invalid Higher temp test (if fan was already spinning high, this is not worrying)
Tests run: 3
```

**Comment by gaul** [comment]
The assert unfortunately does not return a lot of information -- you might try adding more logging to `minunit.c:test_get_temp`.

**Comment by gaul** [comment]
Please test with the recently released [2.1.1](https://github.com/dgraziotin/mbpfan/releases/tag/v2.1.1) which may address this issue.

**Comment by impearker** [comment]
I installed and ran tests with 2.1.1 and all tests passed. You can close this. Yay.

**Comment by gaul** [comment]
Thank you for the feedback!
