### ISSUE TITLE
Something wrong with app

### ISSUE THREAD

**Issue by Markospoko** [dgraziotin/mbpfan#170]
Could you fix the app? When fans get busy and things get cooler, cooling just stays there high?

**Comment by gaul** [comment]
`mbpfan` should decrease fan speed as temperatures drop.  Can you post the logs from `mbpfan -f -v` demonstrating your symptoms?

**Comment by Markospoko** [comment]
\>\> I boot Lin and sensors give:

applesmc-isa-0300
Adapter: ISA adapter
Left side  : 3003 RPM  (min = 1984 RPM, max = 6000 RPM)
Right side : 3001 RPM  (min = 1984 RPM, max = 6000 RPM)
TB0T:         +33.8°C  
TB1T:         +33.8°C  
TB2T:         +30.2°C  
TC0C:         +60.5°C  
TC0D:         +61.2°C  
TC0P:         +58.0°C  
TC1C:         +63.0°C  
TG0D:         +61.0°C  
TG0P:         +55.0°C  
TG0T:         +60.5°C  
TMCD:         +63.0°C  
TP0P:         +56.8°C  
TPCD:         +63.0°C  
Th1H:         +49.5°C  
Th2H:         +50.0°C  
Tm0P:         +52.0°C  
Ts0P:         +30.0°C  
Ts0S:         +42.8°C

\>\> I run Xonotic and after a while of playing:

applesmc-isa-0300
Adapter: ISA adapter
Left side  : 5397 RPM  (min = 1984 RPM, max = 6000 RPM)
Right side : 5360 RPM  (min = 1984 RPM, max = 6000 RPM)
TB0T:         +34.8°C  
TB1T:         +34.8°C  
TB2T:         +31.0°C  
TC0C:         +68.5°C  
TC0D:         +68.2°C  
TC0P:         +66.5°C  
TC1C:         +70.0°C  
TG0D:         +68.0°C  
TG0P:         +63.8°C  
TG0T:         +67.5°C  
TMCD:         +70.0°C  
TP0P:         +61.0°C  
TPCD:         +66.0°C  
Th1H:         +56.5°C  
Th2H:         +57.8°C  
Tm0P:         +57.5°C  
Ts0P:         +32.0°C  
Ts0S:         +47.5°C

\>\> after leaving temps decrease but slowly, and cooling slows, it gets to:

applesmc-isa-0300
Adapter: ISA adapter
Left side  : 4314 RPM  (min = 1984 RPM, max = 6000 RPM)
Right side : 4322 RPM  (min = 1984 RPM, max = 6000 RPM)
TB0T:         +35.0°C  
TB1T:         +35.0°C  
TB2T:         +31.2°C  
TC0C:         +56.8°C  
TC0D:         +56.8°C  
TC0P:         +54.8°C  
TC1C:         +57.0°C  
TG0D:         +56.5°C  
TG0P:         +51.8°C  
TG0T:         +56.0°C  
TMCD:         +57.0°C  
TP0P:         +55.0°C  
TPCD:         +59.0°C  
Th1H:         +47.5°C  
Th2H:         +47.8°C  
Tm0P:         +50.5°C  
Ts0P:         +31.0°C  
Ts0S:         +42.2°C

\>\> and keeps staying around 4312 - 4324.

My config:
```[general]
# see https://ineed.coffee/3838/a-beginners-tutorial-for-mbpfan-under-ubuntu for the values
min_fan_speed = 3000	# put the *lowest* value of "cat /sys/devices/platform/applesmc.768/fan*_min"
max_fan_speed = 6000	# put the *highest* value of "cat /sys/devices/platform/applesmc.768/fan*_max"
low_temp = 45			# try ranges 55-63, default is 63
high_temp = 66			# try ranges 58-66, default is 66
max_temp = 85			# take highest number returned by "cat /sys/devices/platform/coretemp.*/hwmon/hwmon*/temp*_max", divide by 1000
polling_interval = 1	# default is 7 seconds.

**Comment by gaul** [comment]
Could you run `mbpfan -f -v`?  This will give an idea what it is doing.

**Comment by gaul** [comment]
Your configuration has low_temp = 45 despite the suggested 55-63 values.  mbpfan will not reach the lowest fan speed if the temperature is higher than low_temp.

**Comment by gaul** [comment]
@Markospoko did my suggestion resolve this issue?  If so please close it.

**Comment by Markospoko** [comment]
Perhaps I'll notice 2 things:
- you can make it better so app works more along with the settings, f.e. if I have 40C for low_temp and min_fan_speed set to 2000, when app starts and "sees" 60C it could lift cooling to that temp just like it does when cooling drops when things approach low_temp, I's puzzled with this because I couldn't understand why it's doing something else
- comments in mbpfan.conf could be more accurate, I found also descriptions in mbpfan.c of what low_temp, etc. are and there's a bit of mismatch with what's in config, as I wasn't sure which ones are fine I believed more these in sources

if not that, it's ok now :)

**Comment by gaul** [comment]
1) I'm not sure I understand your suggestion.  Could you open another issue with the current and suggested behavior?

2) Please submit a pull request!  Improved documentation helps all users.
