### ISSUE TITLE
Too hot

### ISSUE THREAD

**Issue by kontheocharis** [dgraziotin/mbpfan#175]
I've got a MacBook Pro 11,5 and it runs way hotter with this script than it does on macOS.
I get about 59-65 just when idle.
Is there a way to fix this? I've tried to tweak the configuration but to no avail...
Unfortunately, the tests can't run due to error message `max_fan_speed value is not 6200`.

**Comment by gaul** [comment]
Could you share your mbpfan version, configuration file, and some log messages from `mbpfan -v -f` when the system is idle and under load?

**Comment by gaul** [comment]
Also I wonder if you use a discrete or integrated GPU?  The former will use more power than the latter.  macOS switches between the two automatically but I am not sure what Linux does.

**Comment by gaul** [comment]
Thanks for sharing this feedback!  Could you share the logs with these settings in case some future user has the same issue?
