### ISSUE TITLE
min_fan_speed

### ISSUE THREAD

**Issue by FrancescoFdd5** [dgraziotin/mbpfan#180]
When i do make tests the output is:

It is normal for them to take a bit to finish.
Could not read min_fan_speed from config file
Tests run: 4

**Comment by impearker** [comment]
I get the same issue.
`User@ComputerName:~/mbpfan-2.1.0$ sudo make tests 
make install
make[1]: Entering directory '/home/parker/mbpfan-2.1.0'
install -d /usr/sbin
install -d /etc
install -d /lib/systemd/system
install -d /usr/share/doc/mbpfan
install bin/mbpfan /usr/sbin
install -m644 mbpfan.conf /etc
install -m644 README.md /usr/share/doc/mbpfan
install -d /usr/share/man/man8
install -m644 mbpfan.8.gz /usr/share/man/man8

******************
INSTALL COMPLETED
******************

A configuration file has been copied (might overwrite existing file) to /etc/mbpfan.conf.
See README.md file to have mbpfan automatically started at system boot.

Please run the tests now with the command
   sudo make tests

make[1]: Leaving directory '/home/User/mbpfan-2.1.0'
/usr/sbin/mbpfan -f -v -t
Starting the tests..
It is normal for them to take a bit to finish.
Using new sensor path for kernel >= 3.15.0 or some CentOS versions with kernel 3.10.0
Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp
Found 3 sensors
Found 1 fans
Using new sensor path for kernel >= 3.15.0 or some CentOS versions with kernel 3.10.0
Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp
Found 3 sensors
Could not read min_fan_speed from config file 
Tests run: 4
`
I have replaced the computer name and my username. This was ran on a 2015 macbook pro running Ubuntu 19.04

**Comment by gaul** [comment]
Please test with the recently released [2.1.1](https://github.com/dgraziotin/mbpfan/releases/tag/v2.1.1) which should address this issue.
