### ISSUE TITLE
Modify Project Banner Thing (Across the top of the Main Section)

### ISSUE THREAD

**Issue by Krutonium** [dgraziotin/mbpfan#184]
Right now it reads "A simple daemon to control fan speed on all MacBook/MacBook Pros (probably all Apple computers) for Linux 3.x.x and 4.x.x" but, with the merging of #183 We know it works on Kernel 5.x.x as well. Perhaps it should be changed to either include 5.x.x or simply Kernel 3 and newer?

**Comment by madmalkav** [comment]
It also works on more computers, i.e. MacPro 1,1 workstations.

**Comment by gaul** [comment]
@dgraziotin I lack the karma to do this; could you modify the banner?  It also would be nice to add GitHub topics as well, e.g., #macbook, #fan, #linux.

**Comment by dgraziotin** [comment]
done! @madmalkav, feel free to report on your tested machines with a PR to README.md.
