### ISSUE TITLE
fan never starts

### ISSUE THREAD

**Issue by csabahenk** [dgraziotin/mbpfan#186]
I discovered my laptop is now deadly silent when mbpfan.service is started, fan does not kick in whatever load I put on it.

I tried eg. this as synthetic test:

```
$ cat /proc/cpuinfo | grep ^processor | ruby -e '(0...STDIN.readlines.size).map {|i| Process.fork { p [i,$$]; loop {} } }.each{Process.wait }'
```

ie. busy looping on all CPUs, but of course real life presents heavy loads much enough.

Fan kicks in immediately if I stop the service.

Earlier it worked fine, fan stopped normally and started on heavy load.

- Hardware: MacBook Air "11 2012
- Kernel: 5.1.7-arch1-1-ARCH
- mbpfan: 2.1.1.r3.gd63fa7c-1

**Comment by csabahenk** [comment]
Some diagnostics... I don't know if it's relevant to the issue but this is what I observed.

I chekched `mbpfan -t`, it gives following error message:

```
Error: max_fan_speed value is not 6200
```

I get it if I run from an ordinary location, ie. not from mbpfan source tree where the _mbpfan.conf.test0_ files are present. I don't get it in the source tree. 

I had the default _mbpfan.conf_, but thought maybe explicitly setting `max_fan_speed` as suggested in the comment would make a difference. It didn't, I still got the error.

Recompiled with this change:

```diff
diff --git a/src/minunit.c b/src/minunit.c
index 2818b50..b089c34 100644
--- a/src/minunit.c
+++ b/src/minunit.c
@@ -135,6 +135,7 @@ static const char *test_settings()
     fan->next = NULL;
 
     retrieve_settings("./mbpfan.conf.test1", fan);
+    printf("max_fan_speed %d\n", fan->fan_max_speed);
     mu_assert("max_fan_speed value is not 6200", fan->fan_max_speed == 6200);
     mu_assert("polling_interval is not 2", polling_interval == 2);

 ```
The printf gives

```
max_fan_speed -1
```

**Comment by gaul** [comment]
Can you run with `mbpfan -f -v` and see what it logs?

**Comment by gaul** [comment]
Do you set `max_fan_speed` to -1 in your mbpfan.conf?

**Comment by csabahenk** [comment]
Just on a cursory glance now mbpfan seem to work. I'll do more thorough testing tomorrow.

I used so far default mbpfan.conf, now when fiddling with it, followed the _put the *lowest/highest* value of "cat /sys/devices/platform/applesmc.768/fan*_min/max"_ instructions to set min/max_fan1_speed. Which are decent positive numbers, not -1.

**Comment by csabahenk** [comment]
Now the service works as I should -- don't know what happened, I didn't even reboot the machine. I'm closing the issue for now, if it again occurs, I'll reopen it.

If you think the mysterious `max_fan1_speed = -1` phenomenon is worth to track down in itself, let me know and I open a dedicated issue for that.
