### ISSUE TITLE
Package for Crux

### ISSUE THREAD

**Issue by jolupa** [dgraziotin/mbpfan#187]
Hi! just created a port for the Crux linux distro.
[you can grab it here](https://github.com/jolupa/jolupalabs/tree/master/mbpfan)
And the fans are working like a charm right now!
Also I'm on a White Macbook from mid 2009.
Thanks

**Comment by gaul** [comment]
Does Crux offer some package management command that we can add to the main README?

**Comment by jolupa** [comment]
Well is little bit weird... You have to add the repo where the package is in [my repo](https://www.github.com/jolupa/jolupalabs) and then make the normal ```prt-get depinst mbpfan```
Also includes the file to start the daemon in the rc.conf.

**Comment by gaul** [comment]
If you can boil this down into one or two commands we can add it to the README.  Otherwise link to your repo with complete instructions.  Please submit a pull request with whichever seems appropriate.

**Comment by gaul** [comment]
Fixed by #189.
