### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by bbtdev** [dgraziotin/mbpfan#188]
dumb question, but how can I uninstall this?

**Comment by dgraziotin** [comment]
If you still have the source file directory, it is a matter of `make uninstall`. If not, please see the [Makefile](https://github.com/dgraziotin/mbpfan/blob/master/Makefile#L42) and execute as root the 5 commands under `uninstall:`

**Comment by bbtdev** [comment]
@dgraziotin thank you. Not acustomed with make
