### ISSUE TITLE
Cleanup Makefile

### ISSUE THREAD

**Issue by oliviertilmans** [dgraziotin/mbpfan#51]
At present it handles many different build config (e.g. building on windows NT, with VS compiler, etc -- while this is a _Linux_ daemon :p) as well as compile everything through g++ while the code is pure C.

Beside the cleanup, I'd add a _debug_ target (to carry the current -g build) and change the _all_ target to build with -O2 as well as edit the install rule to also strip the executable.

**Comment by dgraziotin** [comment]
Fixed in #104 [can you believe it?!?]
