### ISSUE TITLE
Repository renamed to mpbfan

### ISSUE THREAD

**Issue by dgraziotin** [dgraziotin/mbpfan#59]
Just to let you know, the repository was renamed from [dgraziotin/Fan-Control-Daemon](http://github.com/dgraziotin/Fan-Control-Daemon) to [dgraziotin/mbpfan](http://github.com/dgraziotin/mbpfan). Github should automatically redirect everything but, let's doublecheck!

**Comment by dgraziotin** [comment]
@Yamakaky, can you verify if building from AUR still works? Thanks!

**Comment by Yamakaky** [comment]
It works!
