### ISSUE TITLE
Linux 4.0 detection

### ISSUE THREAD

**Issue by Sracinas** [dgraziotin/mbpfan#60]
Hello, I'm using arch linux with kernel 4.0 when i start mbpfan -t i get the following error:

Starting the tests..
It is normal for them to take a bit to finish.
Kernel major version is not 3. 
Tests run: 1

The fix was released 18 days ago, but maybe there is something wrong with it.

**Comment by dgraziotin** [comment]
Hi,

My bad, I have not updated the tests yet for the v.4.x.x kernels. You
should be good to go regardless.
I will update the tests asap and ping you.

On Wed, Apr 15, 2015 at 12:30 PM, Sracinas <notifications@github.com> wrote:

> Hello, I'm using arch linux with kernel 4.0 when i start mbpfan -t i get
> the following error:
>
> Starting the tests..
> It is normal for them to take a bit to finish.
> Kernel major version is not 3.
> Tests run: 1
>
> The fix was released 18 days ago, but maybe there is something wrong with
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dgraziotin/mbpfan/issues/60>.
>



-- 
Daniel Graziotin

Orcid: http://orcid.org/0000-0002-9107-7681
Skype: dgraziotin
Twitter: http://twitter.com/dgraziotin
Website: http://ineed.coffee

**Comment by dgraziotin** [comment]
@Sracinas this has just been fixed in #62 and released in v1.9.1. Thank you for reporting this issue.
