### ISSUE TITLE
Incorrect terminal command in readme

### ISSUE THREAD

**Issue by BrendanEMahon** [dgraziotin/mbpfan#65]
The readme file for systemd says to issue the terminal command "sudo cp mbpfan.service /usr/lib/systemd/system".  After issuing that command it occurred to me that this was likely a directory with a collection of boot services.  I believe the command should be "sudo cp mbpfan.service /usr/lib/systemd/system/mbpfan.service".  I copied the original system folder over from /etc/systemd/system and I'm hoping the contents were equivalent.

**Comment by dgraziotin** [comment]
You are correct. I wrote an [introductory tutorial for mbpfan and Ubuntu](https://ineed.coffee/3838/a-beginners-tutorial-for-mbpfan-under-ubuntu/). The tutorial uses the right path. I am also updating README.md. Thanks!
