### ISSUE TITLE
Test error? on latest Ubuntu with MBP 9,2 13"

### ISSUE THREAD

**Issue by zproc** [dgraziotin/mbpfan#66]
Hello. On a Macbook Pro 9,2 13", i think i already used mbpfan without problem, and on the latest Ubuntu and latest Manjaro-XFCE (based on Arch with the AUR package) i get this when running the tests:

$ mbpfan -t
Starting the tests..
It is normal for them to take a bit to finish.
min_fan_speed value is not 6200 
Tests run: 6

Is it an error? Is it problematic? 
I find the macbook gets hot even while idle or almost idle...

**Comment by dgraziotin** [comment]
Sorry for the delay. Does the issue still persist?
Please make sure to reproduce it
- With a cold boot
- After using the macbook for a while

**Comment by zproc** [comment]
The issue persisted and i think i had the same one on my Mac Mini late 2012 with Elementary OS (Ubuntu 14.04 based) (i know it's not a Macbook but i think i remember it working with this one too.)

Although, i can't try to reproduce it for now, as i found the Macbook was maybe too hot (i wasn't sure and i was afraid of bmpfan not working correctly as i didn't know what the error meant) i switched to Macfanctld and finally found a better setting for the fans with it (still not sure it's perfect). I'll see if i can try to uninstall one and re-install the other to check.

**Comment by dgraziotin** [comment]
I am glad that macfanctld is working fine for your case! Please open a new issue if you can replicate it.
