### ISSUE TITLE
Test error: "min_fan_speed value is not 6200"

### ISSUE THREAD

**Issue by zproc** [dgraziotin/mbpfan#68]
Hello again. 

Macbook Pro 9,2 13" with Ubuntu 15.04, kernel "linux 3.19.0-28-generic" 64 bit

So, I re installed mbpfan and i still have the same problem and the issue persists:

$ mbpfan -t
Starting the tests..
It is normal for them to take a bit to finish.
min_fan_speed value is not 6200 
Tests run: 6

I have this "error" after a cold boot and after having used the computer for a while.

**Comment by markus-git** [comment]
Did you run the tests in a location with a test file in it?

I had the same error. Browsed the code a bit and found 

    static const char *test_settings()
    {
        retrieve_settings("./mbpfan.conf.test1");
        mu_assert("min_fan_speed value is not 6200", min_fan_speed == 6200);
        ...
    }
in " mbpfan/src/minunit.c". 

So, with a copy of the test file in the current directory, running "mbpfan -t" worked.
