### ISSUE TITLE
Upstart: Failed to connect to socket /com/ubuntu/upstart:

### ISSUE THREAD

**Issue by X-s** [dgraziotin/mbpfan#70]
hi, when i was try to use mbpfan on my macbook pro 12,1 (linux kenel 4.2), it has some problems.
can you help me?
i exec "sudo systemctl enable mbpfan.service", then term report to me "Created symlink from /etc/systemd/system/sysinit.target.wants/mbpfan.service to /etc/systemd/system/mbpfan.service."  that look like great, but when i copy mbpfan.upstart to /etc/init/mbpfan.conf and exec sudo start mbpfan, trem has a error "Upstart: Failed to connect to socket /com/ubuntu/upstart". 
thanks

**Comment by Yamakaky** [comment]
`sudo systemctl start mbpfan`

**Comment by X-s** [comment]
it good works, thanks man
