### ISSUE TITLE
Congrat, working out of the box for elderly-fan-noisy macbook-1.1!! 

### ISSUE THREAD

**Issue by nodje** [dgraziotin/mbpfan#73]
just what the title says, it's a thank you message, you saved my ears in a few working cli.
Debian testing on an old Macbook 1,1
```
git clone https://github.com/dgraziotin/mbpfan.git
cd mbpfan/
make
sudo make install
sudo make tests 
sudo mv mbpfan.init.debian /etc/init.d/mbpfan
sudo chmod +x /etc/init.d/mbpfan
sudo update-rc.d mbpfan defaults
service mbpfan start
```
fan went instantly silent ... pfuh it feels so good :D
many thanks!

**Comment by dgraziotin** [comment]
I am glad that it is working well. Care to share the distribution you are running on it? So that I can update the [README](https://github.com/dgraziotin/mbpfan/blob/master/README.md#tested-macbook-models) file

**Comment by nodje** [comment]
It's a [MacBook1,1](https://en.wikipedia.org/wiki/MacBook) running **Debian Testing** based but discontinued [Crunchbang](https://www.bunsenlabs.org/) distrib.
So it's basically Debian, and you support that. What you should add in the README is that it actually works on MacBook1,1.
