### ISSUE TITLE
Gentoo ebuild

### ISSUE THREAD

**Issue by p-kozlov** [dgraziotin/mbpfan#75]
It would be fine to have gentoo ebuild or overlay (can be hosted in github, no need to try to put it in official tree).

**Comment by dgraziotin** [comment]
Absolutely. Care to write and test it?

**Comment by andjscott** [comment]
I have a start [here](https://github.com/andjscott/overlays/blob/master/app-laptop/mbpfan/mbpfan-1.9.1.ebuild)

**Comment by dgraziotin** [comment]
@andjscott thanks! Shall it be integrated in the official tree? Nothing against it.

**Comment by andjscott** [comment]
@dgraziotin I've added my repo to gentoo's overlay list at https://overlays.gentoo.org. Overlays for gentoo are similar to Arch's AUR. Gentoo's layman can be used to add custom lists of ebuilds - having the ebuild there would probably be easier for people to install mbpfan.

**Comment by gktrk** [comment]
Hi,

I've added this package to the official Gentoo repo: https://packages.gentoo.org/packages/app-laptop/mbpfan

Feel free to update the instructions accordingly if you like.

**Comment by dgraziotin** [comment]
That is great, thank you!

**Comment by p-kozlov** [comment]
@gktrk awesome!
