### ISSUE TITLE
New Ubuntu (16.04) uses systemd, not Upstart

### ISSUE THREAD

**Issue by wwoods** [dgraziotin/mbpfan#77]
Therefore the directions for adding it as a service need to be modified to the instructions for systemd.

**Comment by maxpaynestory** [comment]
Please guide me where to change inside the source in-order to get it running on 16.04. My Macbook fan is going crazy.

**Comment by maxpaynestory** [comment]
I got it running by going inside the source folder and copying mbpfan.service to /etc/systemd/system folder

```
sudo cp mbpfan.service /etc/systemd/system
```

and then starting the service as sudo

```
sudo service mbpfan start
```

**Comment by wwoods** [comment]
Exactly, the readme just needs to be updated appropriately.

**Comment by dgraziotin** [comment]
Yup. I'm just waiting to have Internet at home for fixing this. Meanwhile:
https://ineed.coffee/3838/a-beginners-tutorial-for-mbpfan-under-ubuntu is
already updated
