### ISSUE TITLE
Ubuntu 16.04 sudo make install busy

### ISSUE THREAD

**Issue by norbertfuhs** [dgraziotin/mbpfan#78]
Hi I tried to compile mbpfan but all i get is this:

noby@Jupiter:~/Downloads/mbpfan$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
noby@Jupiter:~/Downloads/mbpfan$ make
Linking...
g++  -g -lm src/minunit.o src/settings.o src/daemon.o src/mbpfan.o src/main.o src/strmap.o -lm -o bin/mbpfan
noby@Jupiter:~/Downloads/mbpfan$ sudo make install
make
make[1]: Verzeichnis „/home/noby/Downloads/mbpfan“ wird betreten
Linking...
g++  -g -lm src/minunit.o src/settings.o src/daemon.o src/mbpfan.o src/main.o src/strmap.o -lm -o bin/mbpfan
make[1]: Verzeichnis „/home/noby/Downloads/mbpfan“ wird verlassen
cp bin/mbpfan /usr/sbin
cp: reguläre Datei '/usr/sbin/mbpfan' kann nicht angelegt werden: Das Programm kann nicht ausgeführt oder verändert werden (busy)
Makefile:66: die Regel für Ziel „install“ scheiterte
make: *** [install] Fehler 1
noby@Jupiter:~/Downloads/mbpfan$

**Comment by dgraziotin** [comment]
That is odd. Does this still happen after rebooting?

————————————————
Daniel Graziotin
Twitter: http://twitter.com/dgraziotin
Website: http://ineed.coffee

On 13 May 2016 at 12:29:58, norbertfuhs (notifications@github.com) wrote:

Hi I tried to compile mbpfan but all i get is this:

noby@Jupiter:~/Downloads/mbpfan$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 16.04 LTS
Release: 16.04
Codename: xenial
noby@Jupiter:~/Downloads/mbpfan$ make
Linking...
g++ -g -lm src/minunit.o src/settings.o src/daemon.o src/mbpfan.o src/main.o src/strmap.o -lm -o bin/mbpfan
noby@Jupiter:~/Downloads/mbpfan$ sudo make install
make
make[1]: Verzeichnis „/home/noby/Downloads/mbpfan“ wird betreten
Linking...
g++ -g -lm src/minunit.o src/settings.o src/daemon.o src/mbpfan.o src/main.o src/strmap.o -lm -o bin/mbpfan
make[1]: Verzeichnis „/home/noby/Downloads/mbpfan“ wird verlassen
cp bin/mbpfan /usr/sbin
cp: reguläre Datei '/usr/sbin/mbpfan' kann nicht angelegt werden: Das Programm kann nicht ausgeführt oder verändert werden (busy)
Makefile:66: die Regel für Ziel „install“ scheiterte
make: *** [install] Fehler 1
noby@Jupiter:~/Downloads/mbpfan$

**Comment by norbertfuhs** [comment]
Yes t still happens after rebooting ...
I Installed mbpfan earlier on Ubuntu 15.10 and had now problems but after upgrading to 16.04 I just wanted to reinstall it..
 
coretemp and applesmc are loaded correctly:


oby@Jupiter:~/Downloads/mbpfan$ cd /sys/devices/platform/applesmc.768/
noby@Jupiter:/sys/devices/platform/applesmc.768$ 
noby@Jupiter:/sys/devices/platform/applesmc.768$ cat fan*_min
1500
noby@Jupiter:/sys/devices/platform/applesmc.768$ cat fan*_max
5500
noby@Jupiter:/sys/devices/platform/applesmc.768$ cat /sys/devices/platform/coretemp.*/hwmon/hwmon*/temp*_max
105000
105000
noby@Jupiter:/sys/devices/platform/applesmc.768$

**Comment by dgraziotin** [comment]
Please provide the output of the following command series (to be executed within mbpfan source directory)

```
sudo rm -rf /usr/sbin/mbpfan
make
sudo cp -rf bin/mbpfan /usr/sbin/mbpfan
sudo cp -rf mbpfan.conf /etc/mbpfan.conf
```

The last command is only if you have not yet configured your own mbpfan.conf file.

**Comment by norbertfuhs** [comment]
CLOSED 
It runs! Thanks I didi the following:[sudo] Passwort für noby: 
noby@Jupiter:~/Downloads/mbpfan-1.9.1$ make
Linking...
g++  -g -lm src/minunit.o src/settings.o src/daemon.o src/mbpfan.o src/main.o src/strmap.o -lm -o bin/mbpfan
noby@Jupiter:~/Downloads/mbpfan-1.9.1$ sudo make install
make
make[1]: Verzeichnis „/home/noby/Downloads/mbpfan-1.9.1“ wird betreten
Linking...
g++  -g -lm src/minunit.o src/settings.o src/daemon.o src/mbpfan.o src/main.o src/strmap.o -lm -o bin/mbpfan
make[1]: Verzeichnis „/home/noby/Downloads/mbpfan-1.9.1“ wird verlassen
cp bin/mbpfan /usr/sbin
cp -n mbpfan.conf /etc

******************
INSTALL COMPLETED
******************

A configuration file has been copied to /etc/mbpfan.conf
See README.md file to have mbpfan automatically started at system boot.

Please run the tests now with the command
   sudo make tests

noby@Jupiter:~/Downloads/mbpfan-1.9.1$

**Comment by norbertfuhs** [comment]
noby@Jupiter:~/Downloads/mbpfan-1.9.1$ ls
AUTHORS  Makefile     mbpfan.conf.test1   mbpfan.init.gentoo  mbpfan.service  README.md
bin      mbpfan.conf  mbpfan.init.debian  mbpfan.init.redhat  mbpfan.upstart  src
noby@Jupiter:~/Downloads/mbpfan-1.9.1$ sudo rm -r /usr/sbin/mbpfan 
[sudo] Passwort für noby: 
noby@Jupiter:~/Downloads/mbpfan-1.9.1$ make
Linking...
g++  -g -lm src/minunit.o src/settings.o src/daemon.o src/mbpfan.o src/main.o src/strmap.o -lm -o bin/mbpfan
noby@Jupiter:~/Downloads/mbpfan-1.9.1$ sudo make install
make
make[1]: Verzeichnis „/home/noby/Downloads/mbpfan-1.9.1“ wird betreten
Linking...
g++  -g -lm src/minunit.o src/settings.o src/daemon.o src/mbpfan.o src/main.o src/strmap.o -lm -o bin/mbpfan
make[1]: Verzeichnis „/home/noby/Downloads/mbpfan-1.9.1“ wird verlassen
cp bin/mbpfan /usr/sbin
cp -n mbpfan.conf /etc

******************
INSTALL COMPLETED
******************

A configuration file has been copied to /etc/mbpfan.conf
See README.md file to have mbpfan automatically started at system boot.

Please run the tests now with the command
   sudo make tests

noby@Jupiter:~/Downloads/mbpfan-1.9.1$

**Comment by dgraziotin** [comment]
I have no explanation on what caused this bug, but I am really glad that it is working now. Cheers!

**Comment by norbertfuhs** [comment]
I also have no explanation I'm glad it works now Thank you!
