### ISSUE TITLE
Tested on iMac mid-2011 (21.5 inches, 2.7GHz (actually 2.8)) also known as iMac 12,1

### ISSUE THREAD

**Issue by aviallon** [dgraziotin/mbpfan#81]
Hello @dgraziotin !
I've tested mbpfanon my iMac mid-2011 (21.5 inches, 2.7GHz (actually 2.8)) also known as iMac 12,1 and it works **PERFECTLY** ! Thanks a lot man. I tested it with maximum CPU usage and temperature never exceeded 68°C !
I ran this command to test : `$ openssl speed -multi 64`.
I think you can add this model to your README.md. That's all.

**Comment by aviallon** [comment]
I'm using Archlinux on kernel 4.6.4

**Comment by dgraziotin** [comment]
Thank you again!
