### ISSUE TITLE
Tested on MacMini6,2 (aka 2012)

### ISSUE THREAD

**Issue by rdoursenaud** [dgraziotin/mbpfan#87]
Not an issue per se.

Just wanted to report that I tested your software on my Mac Mini equipped with an i7-3615QM running Arch Linux kernel 4.7.3-4-ck.

The machine is now a bit noisy but I finally got rid of thermal throttling. Thank you!

Here's my config FWIW:
```
[general]
min_fan_speed = 1800
max_fan_speed = 5500
low_temp = 63
high_temp = 66
max_temp = 87
polling_interval = 7
```

**Comment by dgraziotin** [comment]
Hello, thank you very much for your report!

Daniel Graziotin
@dgraziotin
ineed.coffee
