### ISSUE TITLE
Does mbpfan conflict with thermald?

### ISSUE THREAD

**Issue by nmquyet** [dgraziotin/mbpfan#90]
Hi, 

I'm using `mbpfan` and it works correctly. However, following a archlinux installation guide, I do also install `thermald`. Should i leave both of them running at the same time or disable `thermald`.

**Comment by dgraziotin** [comment]
Hello,

I am not familiar with thermald and have no experience with it. Mbpfan is built for Apple devices only, while thermald seems a one-size-fits-all solution. At a first glance yes, mbpfan seems in conflict with thermald with respect to setting the fan speed.

**Comment by nmquyet** [comment]
Thanks, I will try to disable thermald.

**Comment by brosasaki** [comment]
Actually, for anyone coming here for info, it appears thermald only adjusts the CPU frequency and power usage, so it should be compatible (maybe even complimentary) with mbpfan.
https://wiki.debian.org/thermald
