### ISSUE TITLE
mbpfan doesn't work with CentOS 7.3

### ISSUE THREAD

**Issue by benkonrath** [dgraziotin/mbpfan#92]
Thanks for working on this application.

It looks like CentOS 7.3 uses the new sensor path so I made a custom build to skip the `is_legacy_kernel()` function and just hard code the new sensor path.  mbpfan worked fine for me on CentOS 7.2 so I'm pretty sure this is something updated in the kernel. Would it be possible to do feature detection (i.e. look for the new path, then the old path, then fail) instead of using the kernel versions to set the path?

```
# uname -a
Linux amsinckia 3.10.0-514.2.2.el7.centos.plus.x86_64 #1 SMP Wed Dec 7 19:10:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
# lsmod | grep applesmc
applesmc               19308  0 
input_polldev          13896  1 applesmc
```
```
# lsmod | grep coretemp
coretemp               13444  0
```

Unmodified version (using the old sensor path):
```
# mbpfan -f -t
Starting the tests..
It is normal for them to take a bit to finish.
mbpfan could not detect any temp sensor. Please contact the developer.
```
My custom build (using the new sensor path):
```
#  mbpfan -f -t
Starting the tests..
It is normal for them to take a bit to finish.
min_fan_speed value is not 6200 
Tests run: 6
```

**Comment by dgraziotin** [comment]
Hello and thank you for reporting this issue. I was not able to find a fork of mbpfan on your Github profile (I wanted to look at the paths that CentOS uses). 

I hope I got it right: CentOS 7.3 has a 3.10 Linux kernel, but it uses the paths that I thought belonged to Linux kernel >= 3.15. Is that correct? Or does CentOS use a different path system?

**Comment by benkonrath** [comment]
I just cloned your repo but I've now made a fork. Here's the change that I made to get it to work:
https://github.com/benkonrath/mbpfan/commit/f83847a5e5cd326cc327ee2cab858535c6bde62a

I tested this with the stock CentOS kernel as well (I use the CentOS plus kernel for applehid support) it also uses the new sensor path. I'm a bit surprised actually. I know the the RHEL kernel backports features from newer kernels but I didn't think they would break compatibility like this.

Here's the output from the stock CentOS kernel with the my hacked version of mbpfan:
```
# uname -a
Linux amsinckia 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
# mbpfan -f -t
Starting the tests..
It is normal for them to take a bit to finish.
min_fan_speed value is not 6200 
Tests run: 6
```

**Comment by benkonrath** [comment]
Sorry, I didn't actually answer your question. Yes, CentOS 7.3 has a 3.10 kernel but uses the paths from kernel >= 3.15. CentOS 7.2 also has a 3.10 kernel but uses the paths from kernel < 3.15.0 which is why mbpfan worked without problems on CentOS 7.2.

**Comment by dgraziotin** [comment]
Thanks for reporting. The approach you suggest (checking the paths instead of kernel version) is likely the way to go. It might take a while :-)

**Comment by benkonrath** [comment]
@dgraziotin Thanks for working on this issue. I just tested the  new-legacy-kernel-detection branch and it is working on CentOS 7.3. Here's what shows up in `/var/log/messages`:

```
Jan  1 18:01:37 localhost mbpfan: Using new sensor path for kernel >= 3.0.15
Jan  1 18:01:37 localhost mbpfan: Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp
Jan  1 18:01:37 localhost mbpfan: Found 3 sensors
Jan  1 18:01:37 localhost mbpfan: Found 1 fans
```

**Comment by rmusial** [comment]
Tested on Ubuntu 16.10/4.8.0-32-generic #34-Ubuntu using using Clang, so far so good.
