### ISSUE TITLE
Contribute upstream

### ISSUE THREAD

**Issue by fidalgo** [dgraziotin/mbpfan#99]
Sorry for the off-topic, but what would involve to get this amazing work in a upstream project, to avoid the need to install third-party software?

**Comment by dgraziotin** [comment]
Hello! Not sure if I get it with the third-party software part. mbpfan is as "pure" as it gets, as it is just C code. One needs to compile it, configure it, and that's it. 

Anyway, if with _upstream_ you mean to have it pre-compiled and/or packaged for GNU/Linux distros, here is what I am aware of.

Mbpfan is currently available for:
- [Gentoo](https://packages.gentoo.org/packages/app-laptop/mbpfan)
- [Arch](https://aur.archlinux.org/packages/mbpfan-git/)
- [Solus](https://git.solus-project.com/packages/mbpfan/)

Somebody [tried to prepare mbpfan for Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829520), but it seems that the process was stopped.

I have not seen attempts to package mbpfan for Ubuntu, Fedora, and OpenSuse. At least, recent attempts.

What the project would require is maintainers, who need to understand how to create and maintain distro-friendly packages. I would be happy to support the maintainers on the source code side. However, I do not have the time for dealing with the distro rules and formats myself.

**Comment by fidalgo** [comment]
By upstream I mean, merge this work with some other software like lm_sensors.

**Comment by dgraziotin** [comment]
closing this as not planned so far
